listingTypes = {
	current_exhibitions = {
		displayName = _(Current Exhibitions),
		table = ca_occurrences,
		restrictToTypes = [exhibition],
		view = Listing/exhibitions_html.php,
		# Search to use when pulling listing content
		search = ca_occurrences.date:\"after today\",
		sortBy = {
			default = ca_occurrences.date
		},
		sortDirection = {
			default = asc
		}
	}
}