cache_timeout = 3600

# Highlight search terms in results?
do_highlighting = 0


advancedSearchTypes = {
	objects = {
		displayName = _("Artworks"),
		labelSingular = _("Artwork"),
 		labelPlural = _("Artworks"),
		table = ca_objects,
		restrictToTypes = [artwork],
		view = Search/ca_objects_advanced_search_objects_html.php, 
		itemsPerPage = 10,
		
		sortBy = {
			Entity = ca_entity_labels.surname;ca_entity_labels.forename,
			Identifier = ca_objects.idno,
			Name = ca_object_labels.name
		},
		views = {
			images = {
				result_caption = "<div class='card-title'><div class='fw-medium lh-sm fs-5'><ifcount code='ca_entities' min='1' restrictToRelationshipTypes='artist'><unit relativeTo='ca_entities' restrictToRelationshipTypes='artist' delimiter=', '>^ca_entities.preferred_labels</unit><br/></ifcount><i>^ca_objects.preferred_labels.name</i></div></div><ifdef code='ca_objects.date_completed|ca_objects.media'><div class='card-text small lh-sm'>^ca_objects.date_completed<ifdef code='ca_objects.date_completed,ca_objects.media'>, </ifdef><ifdef code='ca_objects.date_completed,ca_objects.media'>^ca_objects.media</ifdef></div></ifdef>",
				image_format = contain, # --- contain or cover - default is cover
			},
			map = {
				mapAttributes = [ca_places.georeference, ca_objects.georeference],
				width = 100%,
				height = 800px,
				minZoomLevel = 2,
				maxZoomLevel = 10,
				mapItemInfoTemplate = "<ifdef code='ca_object_representations.media.widepreview'><div class='img-fluid pb-2'>^ca_object_representations.media.widepreview</div></ifdef><div class='fw-bold fs-5'><l><ifcount code='ca_entities' min='1' restrictToRelationshipTypes='artist'><unit relativeTo='ca_entities' restrictToRelationshipTypes='artist' delimiter=', '>^ca_entities.preferred_labels</unit><br/></ifcount><i>^ca_objects.preferred_labels.name</i></l></div><ifdef code='ca_objects.date_completed|ca_objects.media'><div class='card-text small lh-sm'>^ca_objects.date_completed<ifdef code='ca_objects.date_completed,ca_objects.media'>, </ifdef><ifdef code='ca_objects.date_completed,ca_objects.media'>^ca_objects.media</ifdef></div></ifdef>"
			}
		}
	}
}
views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	},
	timeline = {
		icon = glyphicon-time
	},
	map = {
		icon = glyphicon-globe
	}
}

#
# Other options
#

# default number of results per page/ajax load
defaultHitsPerBlock = 36

# add a wildcard "*" to the end of all searches? 
matchOnStem = 0

advancedSearchBaseClasses = ["form-control"]

advanceSearchFormElementTemplates = {
	__default__ = "<div class='col-md-6'>
						<label for='^ELEMENTID' class='form-label'>^LABEL</label>
						^ELEMENT
						<div id='^DESCRIPTIONID' class='form-text'>
							^DESCRIPTION
						</div>
					</div>"
}


# For searches on Geocode metadata, default search radius when a point location is queried without an explicit radius specified
# Radius can use any standard support dimensional units (m, km, mi, ft...)
geocode_search_default_radius = [500m, 800m, 1600m]

geocode_search_radius_by_type = {
	postcode = [1500m, 2500m],
	commercial = 500m,
	house = [100m, 200m, 400m, 800m],
	amenity = 400m,
	townhall = 250m,
	primary = 1000m,
	secondary = 1000m
	town = 5000m,
	village = 2500m,
	city = 5000m,
	library = 1000m,
	park = [800m, 1600m],
	residential = [200m, 400m, 800m],
	neighbourhood = 1500m,
	museum = [500m, 750m, 1000m],
	college = 1250m,
	hotel = 1000m,
	golf_course = 1250m,
	school = [500m, 1000m],
	pedestrian = [1000m, 2000m]
}

geocode_search_rewrites = {
	us_postalcodes = {
		regexes = {
			"/^([\\d]{5})$/" = "$1 USA"
		},
		mode = postcode
	},
	address_without_city = {
		regexes = {
			"/San Antonio/i" = " ",
			"/Texas/i" = " ",
			"/Tx/i" = " ",
			"/^(.*)$/" = "$1, San Antonio, Texas"
		}
	}
}
