routes = {
	object_puri = {
		method = GET,
		pattern = "/{^identifier}",
		constraints = {
			"identifier" = "/([A]{1}\\-[\\d]+)/i"
		},
		to = {module = "", controller = "Detail", action = "objects/^identifier", params = {}}
	},
	collection_puri = {
		method = GET,
		pattern = "/{^identifier}",
		constraints = {
			"identifier" = "/([C]{1}\\-[\\d]+)/i"
		},
		to = {module = "", controller = "Detail", action = "collections/^identifier", params = {}}
	}
}