# Highlight search terms in results?
do_highlighting = 0


advancedSearchTypes = {
	objects = {
		displayName = _("Objects"),
		labelSingular = _("Object"),
 		labelPlural = _("Objects"),
		table = ca_objects,
		restrictToTypes = [],
		view = Search/ca_objects_advanced_search_objects_html.php, 
		itemsPerPage = 10,
		
		sortBy = {
			Entity = ca_entity_labels.surname;ca_entity_labels.forename,
			Identifier = ca_objects.idno,
			Name = ca_object_labels.name
		},
		views = {
			images = {
				result_caption = "<div class='card-title'><small class='text-body-secondary'>^ca_objects.accession_num</small><div class='fw-medium lh-sm fs-5'><l>^ca_objects.preferred_labels</l><ifdef code='ca_objects.nomenclature'><br/>^ca_objects.nomenclature%delimiter=,_</ifdef><ifdef code='ca_objects.spec_common_name'><br/>^ca_objects.spec_common_name%delimiter=,_</ifdef><ifdef code='ca_objects.source_id'><br/>^ca_objects.source_id</ifdef></div></div>",
			}
		}
	}
}
views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	},
	timeline = {
		icon = glyphicon-time
	},
	map = {
		icon = glyphicon-globe
	}
}

#
# Other options
#

# default number of results per page/ajax load
defaultHitsPerBlock = 36

# add a wildcard "*" to the end of all searches? 
matchOnStem = 0

advancedSearchBaseClasses = ["form-control"]

advanceSearchFormElementTemplates = {
	__default__ = "<div class='mb-3'>
						<label for='^ELEMENTID' class='form-label'>^LABEL</label>
						^ELEMENT
						<div id='^DESCRIPTIONID' class='form-text'>
							^DESCRIPTION
						</div>
					</div>"
}