<?php print $this->render('About/subNav.php'); ?>
<h1>About the Partners</h1>
<div class="textContent">
	<div>
		<div style="float:left; margin:30px 30px 40px 0px; width:190px; text-align:center;"><a href="http://www.oldfilm.org" target="_blank"><img src="<?php print $this->request->getThemeUrlPath(); ?>/graphics/clir2/logo_nhf.jpg" border="0"></a></div>
		<H2>Northeast Historic Film</H2>
		Northeast Historic Film (NHF) is a moving image archives, incorporated as a non-profit organization in 1986. We are located in the Alamo Theatre, a 1916 cinema building, in Bucksport, Maine. Our mission is to collect and preserve the film and video record of northern New England (Maine, New Hampshire, Vermont, and Massachusetts), and to provide public access to the history, culture, and people of the region embodied in it. Our collections contain ten million feet of film and more than 8,000 hours of video; most of these materials are unique and irreplaceable. NHF cares for film from hundreds of northern New England places in a three-story temperature and humidity controlled vault building, which also provides state-of-the-art storage for institutions from throughout the east coast. Collectively our holdings constitute a record of 20th century regional culture seen from countless angles: the factory floor and the farm, in the woods and at sea, at home with our families and on the streets of our hometowns.
	</div>
	<div style="clear:left; padding-top:20px;">
		<div style="float:left; margin:30px 30px 40px 0px; width:190px; text-align:center;"><a href="http://www.eastmanhouse.org" target="_blank"><img src="<?php print $this->request->getThemeUrlPath(); ?>/graphics/clir2/logo_geh.gif" border="0"></a></div>
		<H2>George Eastman House International Museum of Photography and Film</H2>
		The Motion Picture Collection at George Eastman House, one of the major moving image archives in the United States, was begun in 1949 by the first curator of film, James Card (1915-2000). His vision, daring and persistence helped to establish George Eastman House as a leading force in the field with holdings of over 25,000 titles and a collection of stills, posters and papers with over 3 million artifacts. In 1996, The L. Jeffrey Selznick School of Film Preservation was founded in order to provide the next generation of archivists with the training and techniques necessary to continue the work of film restoration in the new millennium.The Selznick School is the first of its kind to provide a comprehensive and intensive training program within the archive environment, thus giving students hands-on experience in all aspects of film handling, conservation, curatorial matters, programming, and both photochemical and digital restoration.
	</div>
	<div style="clear:left; padding-top:20px;">
		<div style="float:left; margin:30px 30px 40px 0px; width:190px; text-align:center;"><a href="http://www.queensmuseum.org" target="_blank"><img src="<?php print $this->request->getThemeUrlPath(); ?>/graphics/clir2/logo_qma.gif" border="0"></a></div>
		<H2>Queens Museum of Art</H2>
		The Queens Museum of Art is dedicated to presenting the highest quality visual arts and educational programming for people in the New York metropolitan area, and particularly for the residents of Queens, a uniquely diverse ethnic, cultural and international community.  The Museum fulfills its mission by designing and providing art exhibitions and educational experiences that promote the appreciation and enjoyment of art, support the creative efforts of artists, and enhance the quality of life through interpreting, collecting, and exhibiting art, architecture, and design.  The museum is based in The New York City Building, which was built to house the New York City Pavilion at the 1939 World's Fair, where it housed displays about municipal agencies.
	</div>	
	<div style="clear:left; padding-top:20px;">
		<div style="float:left; margin:5px 30px 40px 0px; width:190px; text-align:center;"><a href="http://www.clir.org/" target="_blank"><img src="<?php print $this->request->getThemeUrlPath(); ?>/graphics/clir2/logo_clir.jpg" border="0"></a></div>
		<H2>The Council on Library and Information Resources</H2>
		The Council on Library and Information Resources (CLIR) is an independent, nonprofit organization that forges strategies to enhance research, teaching, and learning environments in collaboration with libraries, cultural institutions, and communities of higher learning.  CLIR aspires to transform the information landscape to support the advancement of knowledge.  CLIR administers the Cataloging Hidden Special Collections and Archives program with the support of generous funding from The Andrew W. Mellon Foundation.
	</div>
</div>