# Highlight search terms in results?
do_highlighting = 0


advancedSearchTypes = {
	artworks = {
		displayName = _("Objects"),
		labelSingular = _("Object"),
 		labelPlural = _("Objects"),
		table = ca_objects,
		restrictToTypes = [artwork],
		view = Search/ca_objects_advanced_search_html.php, 
		itemsPerPage = 10,
		
		views = {
			images = {
				#result_caption = "<div class='card-title'><ifdef code='ca_objects.sort_number'><small class='text-body-secondary'>^ca_objects.sort_number</small></ifdef><div class='fw-medium lh-sm fs-5'><l>^ca_objects.preferred_labels</l></div></div><p class='card-text small lh-sm'><ifdef code='ca_objects.print_date'>^ca_objects.print_date<br/></ifdef><ifdef code='ca_objects.medium.medium_notes_text'>^ca_objects.medium.medium_notes_text<br/></ifdef><ifdef code='ca_objects.master_dimensions'>^ca_objects.master_dimensions%delimiter=;_<br/></ifdef></p>",
				result_caption = "<div class='card-title mb-0'><div class='fw-medium lh-sm fs-5'><l>^ca_objects.preferred_labels</l></div></div><p class='card-text lh-sm'><ifdef code='ca_objects.print_date'>^ca_objects.print_date</ifdef></p>",
				image_format = contain, # --- contain or cover - default is cover
			}
		},
		sortBy = {
			Number = ca_objects.sort_number,
			Date = ca_objects.common_date,
			Title = ca_object_labels.name
		},
		# --- default sort direction for the sortBy options
		sortDirection = {
			Identifier = asc,
			Date = asc,
			Title = asc
		},
		baseCriteria = {
			classification_facet = [361],
		}
	}
}
views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	},
	timeline = {
		icon = glyphicon-time
	},
	map = {
		icon = glyphicon-globe
	}
}

#
# Other options
#

# default number of results per page/ajax load
defaultHitsPerBlock = 36

# add a wildcard "*" to the end of all searches? 
matchOnStem = 0

advancedSearchBaseClasses = ["form-control"]

advanceSearchFormElementTemplates = {
	__default__ = "<div class='col-md-6'>
						<label for='^ELEMENTID' class='form-label'>^LABEL</label>
						^ELEMENT
						<div id='^DESCRIPTIONID' class='form-text fs-5 text-black'>
							^DESCRIPTION
						</div>
					</div>"
}