const exhibitions = [
  "Keith Haring: The SVA Years 1978 - 1980",
  "John Ehrenclou, Keith Miller, Daniel Traub",
  "Works of Nine Young Artists: Peter Allen, Liz Belveal, Faris El Maati, Candace Mate, Timothy McNabb, Ron Meisner, Fernando Montoya-Nino, Antonella Piemontese, Keith Ragone",
  "Ten Young Artists: Peter Allen, Judy Geib, John Hamilton, Emma Harvin, Candace Mate, Ron Meisner, Aeyung Park, Antonella Piemontese, Keith Ragone, Mitsuo Toshida",
  "Fine Art: A.A. El Kammass, Faris El Maati, Pamela Kelly, Moira McCarty, Fernando Montoya-Nino, Keith Ragone, Angel Suarez",
  "Thesis Show 2013",
  "Selections from the MFA Special Project (1985)",
  "New Talent",
  "8 Artists / 8 Years",
  "Beginning Here: 101 Ways",
  "School of Visual Arts: Fine Arts Alumni 1977-1987: Selected Works",
  "Mentors (2004)",
  "Keith Haring: The SVA Years 1978 - 1980",
  "John Ehrenclou, Keith Miller, Daniel Traub",
  "Works of Nine Young Artists: Peter Allen, Liz Belveal, Faris El Maati, Candace Mate, Timothy McNabb, Ron Meisner, Fernando Montoya-Nino, Antonella Piemontese, Keith Ragone",
  "Ten Young Artists: Peter Allen, Judy Geib, John Hamilton, Emma Harvin, Candace Mate, Ron Meisner, Aeyung Park, Antonella Piemontese, Keith Ragone, Mitsuo Toshida",
  "Fine Art: A.A. El Kammass, Faris El Maati, Pamela Kelly, Moira McCarty, Fernando Montoya-Nino, Keith Ragone, Angel Suarez",
  "Thesis Show 2013",
  "Selections from the MFA Special Project (1985)",
  "New Talent",
  "8 Artists / 8 Years",
  "Beginning Here: 101 Ways",
  "School of Visual Arts: Fine Arts Alumni 1977-1987: Selected Works",
  "Mentors (2004)",
]

export default exhibitions;