const people = [
  "Moses Bigby", 
  "Dorothy Tober", 
  "Lavenia Westhoff",
  "Nathanial Parillo",
  "Cassi Mcelhannon",
  "Raquel Hartlage",
  "Lucille Padron",
  "Truman Summey",
  "Sarah Mclachlan",
  "Barbera Simonetti",
  "Mark Benfer",
  "Blake Mapp",
  "Edris Tellier",
  "Tawnya Magness",
  "Darlena Dulmage",
  "Alexandria Craddock",
  "Katelyn Pulice",
  "Mabelle Beckles",
  "Crystal Farrish",
  "Talitha Kuester",
  "Ophelia Taylor",
  "Kandy Harford",
  "Daisy Klausner",
  "Forest Brinks",
  "Diann Boser",
  "Sheilah Cunniff",
  "Drema Caperton",
  "Felicidad Ebron",
  "Corina Laramore",
  "Lakiesha Patti",
  "Mabelle Beckles",
  "Crystal Farrish",
  "Talitha Kuester",
  "Ophelia Taylor",
  "Kandy Harford",
]

export default people;