dont_moderate_comments = 0
dont_email_notification_for_new_comments = 0

email_notification_for_new_registrations = 1

lightbox_default_access = 1


ca_objects_alt_text_template = "<case><ifdef code='ca_objects.title'>^ca_objects.title</ifdef><ifnotdef code='ca_object_representations.preferred_labels.name'>^ca_objects.preferred_labels.name</ifnotdef><if rule='^ca_object_representations.preferred_labels.name =~ /[BLANK]/'>^ca_objects.preferred_labels.name</ifnotdef><if rule='^ca_object_representations.preferred_labels.name !~ /[BLANK]/'>^ca_object_representations.preferred_labels.name</ifnotdef></case>"
ca_object_representations_alt_text_template = "<case><ifdef code='ca_objects.title'>^ca_objects.title</ifdef><ifnotdef code='ca_object_representations.preferred_labels.name'>^ca_objects.preferred_labels.name</ifnotdef><if rule='^ca_object_representations.preferred_labels.name =~ /[BLANK]/'>^ca_objects.preferred_labels.name</ifnotdef><if rule='^ca_object_representations.preferred_labels.name !~ /[BLANK]/'>^ca_object_representations.preferred_labels.name</ifnotdef></case>"
