# Highlight search terms in results?
do_highlighting = 0


advancedSearchTypes = {
	events = {
		displayName = _("Events"),
		labelSingular = _("Event"),
 		labelPlural = _("Events"),
		table = ca_occurrences,
		restrictToTypes = [],
		view = Search/ca_events_advanced_search_html.php, 
		itemsPerPage = 36,
		
		views = {
			list = {
				result_caption = "<div class='card-title'><div class='fw-medium lh-sm fs-4'>^ca_occurrences.preferred_labels</div><ifdef code='ca_occurrences.common_date|ca_occurrences.event_type'><small class='text-body-secondary'>^ca_occurrences.common_date<ifdef code='ca_occurrences.common_date,ca_occurrences.event_type'>, </ifdef>^ca_occurrences.event_type</small></ifdef></div>",
				#image_format = contain, # --- contain or cover - default is cover
				list_format = text_list, # --- image or text where text is a simple grid of cards with no media
			},
		},
		
		sortBy = {
			Date = ca_occurrences.common_date,
			Name = ca_occurrence_labels.name
		},

	}
}
views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	},
	timeline = {
		icon = glyphicon-time
	},
	map = {
		icon = glyphicon-globe
	}
}

#
# Other options
#

# default number of results per page/ajax load
defaultHitsPerBlock = 36

# add a wildcard "*" to the end of all searches? 
matchOnStem = 0

advancedSearchBaseClasses = ["form-control"]

advanceSearchFormElementTemplates = {
	__default__ = "<div class='col-md-6'>
						<label for='^ELEMENTID' class='form-label'>^LABEL</label>
						^ELEMENT
						<div id='^DESCRIPTIONID' class='form-text'>
							^DESCRIPTION
						</div>
					</div>"
}