<div class="textContent">
	<div style="float:left; width:580px; padding-left:20px;">
		Here are a few recommendations for beginning your journey through the Permanent Collection. Browse by artist name, media, country of origin, and other terms through the links provided to the left, or browse by collection based on the descriptions below. Objects are added and records updated continually.
	</div>
	<div style="clear:left;">
		<b>Ancient and Classical Art</b>
		<br/>Many of the first objects to enter the Museum's collection were Egyptian antiquities, including pottery from the Pre-Dynastic to the Twenty-Sixth Dynasty, and a table of offering from the First Intermediate Period.  Highlights include a recently acquired <?php print caNavLink($this->request, 'sarcophagus', '', 'Detail', 'Object', 'Show', array('object_id' => 18348)); ?> from the Twenty-Sixth Dynasty. The collection also contains classical pottery, such as a <?php print caNavLink($this->request, 'Greek Apulian amphora', '', 'Detail', 'Object', 'Show', array('object_id' => 1366)); ?> from the fourth century BCE, and a later <?php print caNavLink($this->request, 'Greco-Roman sarcophagus', '', 'Detail', 'Object', 'Show', array('object_id' => 8635)); ?> from the Constantinian period.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse Ancient and Classical Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 3)); ?>
	</div>
	<div>
		<b>Asian Art</b>
		<br/>The Asian collection contains Hindu and Buddhist sculptures from South and Southeast Asia, while works from the Far East include primarily secular paintings, ceramics, textiles, and decorative objects.  Highlights of this collection include sculptures from the Chinese Ming dynasty, an Ayutthaya period <?php print caNavLink($this->request, 'Walking Buddha', '', 'Detail', 'Object', 'Show', array('object_id' => 1648)); ?> from Thailand, and a twentieth century <?php print caNavLink($this->request, 'Shiko Munakata', '', 'Detail', 'Entity', 'Show', array('entity_id' => 2027)); ?> Japanese woodblock print.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse Asian Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 4)); ?>
	</div>
	<div>
		<b>African, Oceanic and New World Art</b>
		<br/>The collection of African art includes more than 2,000 objects from many cultures. The UMFA's holdings also include American Indian objects such as Navajo weavings, Pueblo pottery, and Northwest Coast masks, like a <?php print caNavLink($this->request, 'Raven Mask', '', 'Detail', 'Object', 'Show', array('object_id' => 4481)); ?> from the Kwakiutl tribe of British Columbia.  Pre-Columbian highlights of the collection include Mayan terracotta funerary figures from the island of Jaina. The core of the Oceanic collection comes from the Asmat people of New Guinea.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse African Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 5)); ?>, <?php print caNavLink($this->request, 'Oceanic Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 6)); ?>, <?php print caNavLink($this->request, 'American Indian Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 7)); ?>, and <?php print caNavLink($this->request, 'Pre-Columbian Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 8)); ?>
	</div>
	<div>
		<b>European Art</b>
		<br/>The UMFA's collection of European art is very strong and represents a millennium of artistic creation. Highlights include works by <?php print caNavLink($this->request, 'Pieter Brueghel the Younger', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1716)); ?>, <?php print caNavLink($this->request, 'Marie-Louise-Elisabeth Vig&eacute;e le Brun', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1771)); ?>, <?php print caNavLink($this->request, 'Jean-Honor&eacute; Fragonard', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1770)); ?>, <?php print caNavLink($this->request, 'Hyacinthe Rigaud', '', 'Detail', 'Entity', 'Show', array('entity_id' => 52)); ?>, and <?php print caNavLink($this->request, 'Jean-Baptiste-Camille Corot', '', 'Detail', 'Entity', 'Show', array('entity_id' => 555)); ?>. Subsets of this collection include Italian and Dutch masterworks.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse European Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 9)); ?>, <?php print caNavLink($this->request, 'The Italian Collection', '', 'Detail', 'Collection', 'Show', array('collection_id' => 10)); ?>, <?php print caNavLink($this->request, 'The Dutch Collection', '', 'Detail', 'Collection', 'Show', array('collection_id' => 11)); ?>
	</div>
	<div>
		<b>American Art</b>
		<br/>The American collection highlights artistic movements of the eighteenth through the twentieth century, including works by <?php print caNavLink($this->request, 'Benjamin West', '', 'Detail', 'Entity', 'Show', array('entity_id' => 266)); ?>, <?php print caNavLink($this->request, 'James Peale', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1464)); ?>, <?php print caNavLink($this->request, 'John Singer Sargent', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1939)); ?>, and <?php print caNavLink($this->request, 'Thomas Cole', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1349)); ?>.  A particular strength of the collection is work by artists who painted in Utah and the American West, such as <?php print caNavLink($this->request, 'LeConte Stewart', '', 'Detail', 'Entity', 'Show', array('entity_id' => 107)); ?>, <?php print caNavLink($this->request, 'Maynard Dixon', '', 'Detail', 'Entity', 'Show', array('entity_id' => 990)); ?>, and <?php print caNavLink($this->request, 'Edgar Payne', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1272)); ?>.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse American Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 12)); ?>
	</div>
	<div>
		<b>Modern and Contemporary Art</b>
		<br/>The UMFA actively collects art from the twentieth and twenty-first centuries. Highlights of the Modern and Contemporary collection include works by <?php print caNavLink($this->request, 'Robert Arneson', '', 'Detail', 'Entity', 'Show', array('entity_id' => 501)); ?>, <?php print caNavLink($this->request, 'Gene Davis', '', 'Detail', 'Entity', 'Show', array('entity_id' => 314)); ?>, <?php print caNavLink($this->request, 'Helen Frankenthaler', '', 'Detail', 'Entity', 'Show', array('entity_id' => 717)); ?>, <?php print caNavLink($this->request, 'Alex Katz', '', 'Detail', 'Entity', 'Show', array('entity_id' => 138)); ?>,  <?php print caNavLink($this->request, 'Sylvia Plimack Mangold', '', 'Detail', 'Entity', 'Show', array('entity_id' => 707)); ?>, <?php print caNavLink($this->request, 'Robert Smithson', '', 'Detail', 'Entity', 'Show', array('entity_id' => 204)); ?>, and <?php print caNavLink($this->request, 'Wayne Thiebaud', '', 'Detail', 'Entity', 'Show', array('entity_id' => 131)); ?>.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse Modern and Contemporary Art', '', 'Detail', 'Collection', 'Show', array('collection_id' => 13)); ?>
	</div>
	<div>
		<b>Photography</b>
		<br/>The Museum's photography collection ranges in materials and techniques, spanning the entire history of the medium. Highlights include salt paper prints from the mid-nineteenth century, early twentieth century albumen prints, and modern works by <?php print caNavLink($this->request, 'Ansel Adams', '', 'Detail', 'Entity', 'Show', array('entity_id' => 2216)); ?>, <?php print caNavLink($this->request, 'Edward Weston', '', 'Detail', 'Entity', 'Show', array('entity_id' => 2137)); ?>, <?php print caNavLink($this->request, 'Weegee', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1943)); ?>, <?php print caNavLink($this->request, 'Jerry Uelsmann', '', 'Detail', 'Entity', 'Show', array('entity_id' => 1218)); ?>, and more.
		<br/>&nbsp;&nbsp;&nbsp;&nbsp;<?php print caNavLink($this->request, 'Browse Photography', '', 'Detail', 'Collection', 'Show', array('collection_id' => 14)); ?>
	</div>
</div>