# Optional routes, used if request does not directly resolve to a module, controller and action
#
routes = {

	# changing /occupations/list to Browse/Occupations	
	occupations = {
		method = GET,
		pattern = "/Browse/occupations",
		to = {module = "", controller = "Occupations", action = "list", params = {}}
	},
	
	gallery = {
		method = GET,
		pattern = "/Resources/Collections",
		to = {module = "", controller = "Gallery", action = "Index", params = {}}
	},
	
	# Example rewrite from Princeton
	object_puri = {
		method = GET,
		pattern = "/{^identifier}",
		constraints = {
			"identifier" = "/([A]{1}\\-[\\d]+)/i"
		},
		to = {module = "", controller = "Detail", action = "objects/^identifier", params = {}}
	}
}
