# Highlight search terms in results?
do_highlighting = 0


advancedSearchTypes = {
	workers = {
		displayName = _(Workers),
		labelSingular = _("worker"),
 		labelPlural = _("workers"),
		table = ca_entities,
		restrictToTypes = [staff],
		view = Search/ca_entities_advanced_search_workers_html.php, 
		#itemsPerPage = 10,
		showLetterBarFrom = ca_entity_labels.surname,
		showLetterBarSorts = [ca_entity_labels.surname;ca_entity_labels.forename],
		views = {
			list = {
				result_caption = "<div class='card-title text-start'><div class='fw-bold lh-sm fs-3'>^ca_entities.preferred_labels</div></div><ifdef code='ca_entities.service_years|ca_entities.occupation'><div class='fw-medium lh-sm fs-5'><ifdef code='ca_entities.occupation'>^ca_entities.occupation%delimiter=,_</ifdef><ifdef code='ca_entities.service_years,ca_entities.occupation'>, </ifdef><ifdef code='ca_entities.service_years'>^ca_entities.service_years%delimiter=,_</ifdef></div></ifdef>",
				list_format = text, # --- image or text where text is a simple grid of cards with no media
			}
		}
		sortBy = {
			Name = ca_entity_labels.surname;ca_entity_labels.forename,
			Date = ca_entities.service_years
		},
		sortDirection = {
			Name = asc,
			Date = asc
		},
		facetGroup = workers
	}
}
views = {
	images = {
		icon = glyphicon-th
	},
	list = {
		icon = glyphicon-list
	},
	timeline = {
		icon = glyphicon-time
	},
	map = {
		icon = glyphicon-globe
	}
}

#
# Other options
#

# default number of results per page/ajax load
defaultHitsPerBlock = 36

# add a wildcard "*" to the end of all searches? 
matchOnStem = 0

advancedSearchBaseClasses = ["form-control"]

advanceSearchFormElementTemplates = {
	__default__ = "<label for='^ELEMENTID' class='form-label'>^LABEL</label>
					^ELEMENT
					<div id='^DESCRIPTIONID' class='form-text'>
						^DESCRIPTION
					</div>"
}

# Regular expression defining punctuation characters to be stripped prior to indexing using
# the SqlSearch2 search engine plugin
punctuation_tokenizer_regex = "[,;:\\(\\)\{\\}\[\\]\\|\\\\\\+\\!\\&«»\\'’\\.]+"