<?php
	MetaTagManager::setWindowTitle($this->request->config->get("app_display_name").": About");
?>

<div class="row">
	<div class="col-sm-1"></div>
	<div class="col-sm-10">
		<H1><?php print _t("History of the Frick Fine Arts Building"); ?></H1>
		<p>With the support of Miss Helen Clay Frick (1888-1984), the Fine Arts Department at the University of Pittsburgh was created in 1927. First housed on the 7th floor of the Cathedral of Learning, Miss Frick endowed the Department with an arts library (now the <a href='http://library.pitt.edu/fine-arts' target='_blank'>Frick Fine Arts Library</a>) and a small gallery for temporary exhibitions. </p>	
		<p>From early on, Pitt’s Chancellor John Bowman and Miss Frick discussed plans to offer the Department its own building. But it was nearly forty years later, under Chancellor Edward Litchfield, that the building was completed. </p>
		<p>The initial designs provided for the Frick Fine Arts Building were vastly different than the final result we see today. Helen Clay Frick and the University consulted several different architects over a period of thirty years, including Charles Klauder (who had designed the Cathedral of Learning), Albert A. Klimcheck, Theodore Bowman (nephew of Chancellor Bowman), and the architectural firm Eggers & Higgins. </p>
		<p>Miss Frick wanted a classical design for the building and a structure that would include classrooms, lecture halls, studios, as well as a library and a gallery.  However, initial attempts at a design solution ended up sacrificing flow and size in order to accommodate these preferences. After many unsuccessful attempts to provide a layout that would satisfy academic needs and a style that would harmonize with the surrounding buildings of Schenley Plaza, Miss Frick turned to W. B. Kenneth Johnstone, former head to the Architecture Department at Carnegie Technical Institute (now Carnegie Mellon University). </p>
		<p>Johnstone and his firm picked up where other architects had left off. He based his design largely on the previous building plans produced by Eggers & Higgins, but decreased the size of the building and eliminated the curved façade that other architects had imagined.</p>
		
		<p>The Oakland building was originally designed to face the Cathedral of Learning, but ended instead towards Schenley Plaza and Hillman Library. Johnstone also worked to incorporate a round cupola, which emulates quattrocento Italian models, such as that in the Church of San Bernardino by Francesco di Giorgio in Urbino. The final plan included the Nicholas Lochoff Cloister containing several Lochoff reproductions of Renaissance art, the Frick Fine Arts Library, the University Art Gallery, and ample classroom space to hold both the Fine Arts and the Studio Arts departments. </p>
		<p>The Frick Fine Arts Building was inaugurated in May 1965. Miss Helen Clay Frick, who financed the building and closely oversaw its construction, named it in memory of her father, steel tycoon Henry Clay Frick (1849-1919). American sculptor Malvina Hoffman (1885-1966) was commissioned to create a relief medallion of Henry Clay Frick, visible on the front limestone façade of the building.</p>
		<p>Miss Frick remained an important and active patron up until her severance with the university in 1968. Her personal collection is now housed at the <a href='http://www.thefrickpittsburgh.org' target='_blank'>Frick Art and Historical Center</a> in Point Breeze, Pittsburgh.  </p>
		<p>As predicted by Professor and Department Chair Walter Read Hovey in a 1963 lecture, the Frick Fine Arts building has become "an ornament to the city and an important influence in its cultural activities."</p>
		<p>The Frick Fine Arts Building is home to two dynamic departments and academic resources. The History of Art and Architecture Department inspires its students to pursue an understanding of the cultural products that have been produced over time, and their relationship with the world. The Studio Arts Department seeks to explore the visual arts through programs aiming to foster new skills and ways for creative problem solving. The University Art Gallery cares for the University's art collection and offers rotating exhibitions each academic semester. The Frick Fine Arts Library, founded in the early years of the Fine Arts department, is ranked among the top art libraries in the country. The Visual Media Workshop, created in 2010, is a digital humanities lab working to investigate material and visual culture using technological experimentation. </p>
		
		<p>The building often provides a public forum for guest lecturers in the large auditorium and hosts University events in the cloister. The University’s General Education requirements make it likely that every Pitt student will take at least one course in the Frick Fine Arts Building. We hope that students and users of the building will notice the care and attention that went into creating this beautiful monument. It endures as a testament to great craftsmanship and the University community’s active support of the arts and the humanities. </p>
		<p><i>For a more detailed synopsis of the architectural processes behind the creation of the Frick Fine Arts Building, see Professor Franklin Toker’s exhibition catalogue, Planning the Pitt Campus: Dreams and Schemes Never Realized, with contributions from graduate students in his seminar on Methods in Architectural History in 1993, and available in the Fine Arts Library (call number: LD6014 P55 1993). </i></p>
		<p><i>Credits and special thanks to Lydia Andeskie, undergraduate student in the History of Art and Architecture department, for compiling research notes and writing texts on the history of the building for its 50th anniversary in 2015. This description of the building is based on her essay. </i></p>			
	</div>
	<div class="col-sm-1"></div>
</div>