<div id="SitePage_Biography"><a name="top" id="top"></a>
	<div id="contentInner">
	<h2>Biography</h2>
	
	<h3>Charles A. Csuri</h3>
	<div class='dotDivide'></div>
	
	<p>Charles A. Csuri is an artist and computer graphics pioneer and Professor Emeritus, at The Ohio State University. He exhibited his paintings in New York City from 1955–1965. His early work is in the collections of Walter P. Chrysler, movie actor Jose Ferrer, pop artist Roy Lichtenstein and sculptor George Segal.</p>
	<p>In 1964, he experimented with computer graphics technology and in 1965 he began creating computer animated films. The 4th International Experimental Film Festival, Brussels, Belgium, 1967, awarded him the prize for animation. His work was highlighted in the exhibition Cybernetic Serendipity held at The Institute for Contemporary Art, London, England, 1968. One of Charles Csuri's computer films is in the collection of New York's Museum of Modern Art.</p>
	<p>His research activity in computer animation and graphics has received international recognition and acclaim. He has been interviewed twice on the Today Show. CNN's Portrait of America featured him on a program and he has been on Entertainment Tonight.</p>
	<p>He received additional television coverage involving interviews about his work in Sweden, England, France, Italy, Spain, Holland, Germany, and Japan. Csuri has lectured and presented his work in Sweden, England, France, Spain, Holland, Italy and Japan.</p>
	<p>With support from the National Science Foundation, the Navy, and the Air Force Office of Scientific Research, he directed basic research in computer graphics for over 22 years. This research activity involved 15 major projects and over eight million dollars. More than forty graduate students in computer science were engaged in the research. In addition, there were over fifty students from the field of art.</p>
	<p>The results of the research have been applied to flight simulators, computer-aided design, visualization of scientific phenomena , magnetic resonance imaging, education for the deaf, architecture, and special effects for television and films.</p>
	<p>Graduates from his program are employees of Industrial Light and Magic, Pacific Data Images, Metro Light, Pixar, Rezn8, Silicon Graphics Inc., USA Today, Rhythm and Hues, Xaos, Walt Disney Productions and others. His former students have worked on such films as Star Wars, Terminator 2, Lawnmover Man, Jurrasic Park, Casper, Toy Story, Monsters, Ice Age and more.</p>
	<p>Douglas Davis the noted art critic included Csuri's work in his book Art and the Future. He also wrote about his work in Newsweek magazine. Davis used Csuri's work as a means to make an important commentary about the future and the significance of computers and art. Charles Csuri's work has been included in over 12 books dealing with computer art and digital media. Recently, a book Digital Art, by Christiane Paul, the curator of New Media Arts at New York's Whitney Museum includes four of his works.</p>
	<p>Csuri received the Distinguished Research Award from The Ohio State University in 1983. He was the keynote speaker at Nicograph, Tokyo, Japan, 1984 and 1992, an international computer graphics conference. He co-founded Cranston / Csuri Productions, which produced animation for all three major U.S. television networks, commercial clients, and The Living Body, a series of 24 television programs which the BBC has distributed worldwide. The Visual Communications Congress, New York, gave him the Golden Eagle award in 1985.</p>
	<p>He exhibited at the 42nd Biennale de Venezia, Italy, 1986 and the Smithsonian in Washinton D.C., 1990. Ars Electronica a major international competition on computers and the arts held in Austria each year, awarded him prizes in 1989 and 1990. (This competition is sponsored by Siemans with over $100,000 in prizes.)</p>
	<p>Dr. Maurizio Calvesi, the highly regarded art historian and art critic wrote a very supportive commentary about his artwork in the prestigious Italian magazine Art and Dossier, November, 1990.</p>
	<p>A Ph.d dissertation was completed on Charles Csuri's Art and Research at New York University in 1991. The dissertation documents the historical significance of Csuri's work and it represents the first attempt to develop a phenomenological tool for evaluating computer images.</p>
	<p>The Smithsonian Magazine, February, 1995 used one of his images for the cover and included a major article about his work and career. Siggraph the International Computer Graphics Conference in 1998 (50,000 attendees) exhibited his art work, used one of his images on the cover of their proceedings, and honored him at a special reception.</p>
	<p>Siggraph has also offically recognized him as a computer graphics pioneer. A photographic portrait of Charles Csuri is now in the Computer Museum, Boston, Massachusetts.</p>
	<p>Ohio State University awarded him the Joseph Sullivant Medal which is their highest honor. The award is made on the basis of alumni or a faculty member's work which has had a significant impact upon society. It is awarded only once every five years. The selection is made by a faculty committee as well as an external review committe.</p>
	<p>Matthew Mirapaul of the New York Times wrote a review of Siggraph's Retrospective for Pioneer of Computer-Based Art. He included a statement by Barbara London of the Museum of Modern Art. "What [Csuri] did was way ahead of his time," said Barbara London, MOMA's associate curator of film and video. "I put him in a league with people like Ed Emshwiller, who came out of painting and science-fiction illustration. They really had a vision of how to use these tools."</p>

	<p class="top"><a href="#top" class="top" title="Back to Top">ˆ Back to Top</a></p>
	</div>
</div>