<div id="SitePage_Browse_Collection"><div id="contentInner">
<?php
	print caGetThemeGraphic($this->request, 'title_collection.gif');
?>
<br>
<br>
<br>

<div id="csuriDownload">
	<p><strong>Charles A. Csuri: Beyond Boundaries</strong><br>
	Exhibition Catalogue<br>
	<a href="/themes/osu/assets/pawtucket/files/charles_a_csuri_beyond_boundries.pdf" title="Exhibition PDF Download">Download PDF Here</a></p>
</div>
<div class="row">
	<div id="box1" class="box col-sm-8 col-md-8 col-lg-8">
		<h2>Art</h2>
	<?php
		print caGetThemeGraphic($this->request, 'block1.jpg');
	?>
		<br/>
		<br/>
		<h7>Early Art 1945–1973</h7>
		<hr>
		<ul>
			<li class="link"><?php print caNavLink($this->request, "» Traditional Works, 1945–1965", "", "", "Detail", "collections/24"); ?></li>
			<li class="lidef">Drawings, paintings and sculptures in traditional media. </li>
			<li class="link"><?php print caNavLink($this->request, "» Pop Art, 1964–1965", "", "", "Detail", "collections/22"); ?></li>
			<li class="lidef">Early works in Pop Art style.</li>
			<li class="link"><?php print caNavLink($this->request, "» Transitional Works, 1962–1965", "", "", "Detail", "collections/25"); ?></li>
			<li class="lidef">Drawings, paintings and analogue computer art created during the transition from traditional art to computer art.</li>
			<li class="link"><?php print caNavLink($this->request, "» Historical Sketches, 1964–1966", "", "", "Detail", "collections/27"); ?></li>
			<li class="lidef">Sketches made while Csuri processed the fine art world's early, and often negative, attitude toward computer art.</li>
			<li class="link"><?php print caNavLink($this->request, "» Plotter Drawings and Sculpture, 1966–1970", "", "", "Detail", "collections/21"); ?></li>
			<li class="lidef">Early drawings and digitally generated sculpture made with a main frame computer, punch cards and a drum plotter.  Includes  still images from the fragmentation animations and randomness series.</li>
			<li class="link"><?php print caNavLink($this->request, "» Fragmentation Animations, 1968–1970", "", "", "Detail", "collections/19"); ?></li>
			<li class="lidef">Early animations that show the electronic "morphing" of Csuri's hand drawing.</li>
			<li class="link"><?php print caNavLink($this->request, "» Real-time Art, 1969–1973", "", "", "Detail", "collections/23"); ?></li>
			<li class="lidef">Art objects that allow the user to participate in determining the final aesthetic object.</li>
		</ul>

		<h7>Later Art 1989–present</strong></h7>
		<hr>
		<ul>
			<li class="link"><?php print caNavLink($this->request, "» 1987–1991", "", "", "Detail", "collections/12"); ?></li>
			<li class="lidef">Csuri's return to making art. Includes works that combine oil paintings, drawings and computer art.</li>
			<li class="link"><?php print caNavLink($this->request, "» 1992–1995", "", "", "Detail", "collections/13"); ?></li>
			<li class="lidef">Works made with Csuri's developing toolkit. Includes color space, fragmentation, texture maps, FRANK, and early AL language developments.</li>
			<li class="link"><?php print caNavLink($this->request, "» 1996–1999", "", "", "Detail", "collections/14"); ?></li>
			<li class="lidef">Works created using mature versions of AL language and other customized tools.</li>
			<li class="link"><?php print caNavLink($this->request, "» Virtual Reality Modeling Language (VRML), 1998", "", "", "Detail", "collections/34"); ?></li>
			<li class="lidef">A later exploration of Csuri's early Real-time, interactive art.</li>
			<li class="link"><?php print caNavLink($this->request, "» Virtual Glass, 1999–2000", "", "", "Detail", "collections/26"); ?></li>
			<li class="lidef">Works that explore the properties of glass in 3-D space.</li>
			<li class="link"><?php print caNavLink($this->request, "» Infinity Series, 2001–present", "", "", "Detail", "collections/17"); ?></li>
			<li class="lidef">Includes Csuri's Generative Art objects and related works. All works in this category are still images.</li>
			<li class="link"><?php print caNavLink($this->request, "» Generative Movement Art, 2006–present", "", "", "Detail", "collections/35"); ?></li>
			<li class="lidef">Abstract art objects generated by continuous random movement. All works in this category are moving objects.</li>
		</ul>

		<p><strong>Research Groups and Commerical Work 1971–1987</strong></p>
		<hr>
		<ul>
			<li class="link"><?php print caNavLink($this->request, "» Computer Graphics Research Group (CGRG), 1971–1987", "", "", "Detail", "collections/15"); ?></li>
			<li class="lidef">Art and animations made within the context of Csuri's interdisciplinary Computer Graphics Research Group.  Also see the "Real-time Art" collection above.</li>
			<li class="link"><?php print caNavLink($this->request, "» Cranston/Csuri Productions, Inc. (CCP), 1981–1987", "", "", "Detail", "collections/16"); ?></li>
			<li class="lidef">Art and animations made by the commercial entity Cranston/Csuri Productions, Inc., which Csuri co-founded.</li>
			<li class="link"><?php print caNavLink($this->request, "» Advanced Computing Center for the Arts and Design (ACCAD), 1987–present", "", "", "Detail", "collections/33"); ?></li>
			<li class="lidef">Csuri and Thomas Linehan established ACCAD (formerly CGRG) at Ohio State, just prior to Csuri's retirement in 1990. For more about ACCAD, see <a href="http://www.accad.osu.edu" title="ACCAD Web Site">accad.osu.edu</a>.</li>
		</ul>
	</div><!-- end box1-->
	<div id="rightCollections" class="col-sm-4 col-md-4 col-lg-4">
		<div id="box2" class="box">
			<h2>Writings</h2>
<?php
			print caGetThemeGraphic($this->request, 'block2.jpg');
?>
			<ul>
				<li class="link"><?php print caNavLink($this->request, "» Essays", "", "", "Browse", "objects/facet/collection_facet/id/28"); ?></li>
				<li class="link"><?php print caNavLink($this->request, "» Grants", "", "", "Browse", "objects/facet/collection_facet/id/29"); ?></li>
				<li class="link"><?php print caNavLink($this->request, "» Letters", "", "", "Browse", "objects/facet/collection_facet/id/30"); ?></li>
				<li class="link"><?php print caNavLink($this->request, "» Interviews", "", "", "Browse", "objects/facet/type_facet/id/27"); ?></li>
				<li class="link"><?php print caNavLink($this->request, "» Exhibition Catalogs", "", "", "Browse", "objects/facet/type_facet/id/26"); ?></li>
			</ul>
		</div>

		<div id="box3" class="box">
			<h2>Life Events</h2>
<?php
			print caGetThemeGraphic($this->request, 'block3.jpg');
?>
			<ul>
				<li class="link"><?php print caNavLink($this->request, "» Personal", "", "", "Listing", "personal");?></a></li>
				<li class="link"><?php print caNavLink($this->request, "» Professional", "", "", "Listing", "professional");?></a></li>
			</ul>
		</div>
	</div><!-- end rightCollections-->
</div><!-- end row-->

</div></div>