# Code of set to render on front page
set_code = frontPage
set_code_entities = frontPageEntities

# show multiple slides (images) or one at a time
set_show_multiple_slides = 0

# Template for caption text under each display object
set_item_caption_template = "<l class='pt-3 pb-4 px-3 d-flex align-items-center justify-content-center bg-body-tertiary h-100 w-100 text-black'>^ca_objects.preferred_labels.name</div>"
set_item_caption_template_entities = "<l class='pt-3 pb-4 px-3 d-flex align-items-center justify-content-center bg-body-tertiary h-100 w-100 text-black'>^ca_entities.preferred_labels.displayname</div>"

# Randomize order of set?
set_random = 1
set_random_entities = 1

# Restrict display of set items by object intrinsic values
# Set each intrinsic field code as a key, with the values to filter by in a list
intrinsic_filter = {}
