#
# Defines listings supported by Listing controller
#
#
listingTypes = {
	series = {
		displayName = _(Series),
		table = ca_collections,
		restrictToTypes = [series],
		view = Listing/ca_collections_listing_subview_html.php,
		sortBy = {
			Identifier = ca_collections.idno,
			Name = ca_collection_labels.name
		},
		sortDirection = {
			Identifier = asc,
			Name = asc
		}
	}
}