enabled = 1
mode = absolute
threshold = 0.9

ip_whitelist = [
    198.110.85.*
    88.99.218.202
    88.99.149.30
    88.99.162.232
    149.56.240.229
    51.79.176.191
    51.222.153.207
    139.99.121.235
    94.130.54.189
    116.202.85.24
    88.99.29.101
]

plugins.UserAgent = {
    banned_useragents = [
         "DataForSeoBot",
         "MJ12bot",
         "AhrefsBot",
         "SemrushBot",
         "opensiteexplorer",
         "UCBrowser",
         "serpstatbot",
         "LieBaoFast",
         "Bytespider",
         "zh-CN",
         "splash",
         "DotBot",
         "BLEXBot",
         "PetalBot",
         "Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)",
         "Barkrowler",
         "webmeup",
         "anth",
         "msie",
         "trident",
         "ahref",
         "sift",
         "owler",
         "android",
         "edg",
         "GPTBot",
         "amazonbot",
         "ImagesiftBot",
         "meta-externalagent",
         "meta-externalagent/1.1 (+https://developers.facebook.com/docs/sharing/webmasters/crawler",
         "Thinkbot",
	 "SemanticScholarBot" 
    ]

    # Ban user agent on dynamically loaded list?
    use_useragent_list = 0,
    
    # URL for user agent ban list. List is JSON in the format defined at https://github.com/monperrus/crawler-user-agents
    useragent_list_url = "https://raw.githubusercontent.com/monperrus/crawler-user-agents/refs/heads/master/crawler-user-agents.json",
    
    # Time in seconds between refreshed of user agent ban list
    useragent_list_ttl = 21600,
    
    # List of user agent patterns to always pass (eg. exclude from useragent list)
    exclude_useragents = [],
    
    # Force reload of user agent list regardless of ttl
    useragent_list_force_reload = 0
}


plugins.RequestFrequency = {
    # Maximum number of page loads per second allows before we ban
    frequency_threshold = 20,

    # Ban weight to return (1.0 = absolutely ban)
    ban_probability = 1.0,
}


plugins.ExportFrequency = {
    # Maximum number of exports per second allows before we ban
    frequency_threshold = 5,

    # Maximum number of exports in a session before we ban
    # (set to zero for no limit)
    allowed_exports_per_session = 10,

    # Ban weight to return (1.0 = absolutely ban)
    ban_probability = 1.0,


plugins.IPAddress = {
	# Duration of ban (in seconds)
	ttl = 86400,

    # List of ip addresses to ban
    # You may use wildcards to match ranges
    # Eg. 10.55.*.*
    banned_ip_addresses = [
        10.44.2.*
	209.240.14.29
	47.246.*.*
    ]

    # Use external banned ip address list?
    use_ip_ban_feed = 0,
    
    # URL of banned ip address list
    # Format is that used in https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt
    # This is a tab-delimited file with two columns: IP address and number of times IP shows up the
    # ban lists used to create the aggregated list. This count can be taken as a measure of certainty about
    # the ip address - if it shows up in many lists it's more likely to be a problem.
	ip_ban_feed_url = "https://raw.githubusercontent.com/stamparm/ipsum/master/ipsum.txt",
	
	# Time in seconds between refreshed of ip ban list
	ip_ban_feed_ttl = 86800,
	
	# Force reload of banned ip list regardless of ttl
	ip_ban_feed_force_reload = 0,
	
	# Minimum value of the ip "count." Addresses with counts below this value will be ignored.
	ip_ban_occurrence_threshold = 2,

}
