<?php
global $g_ui_locale;
?>
<?php
if($g_ui_locale=="de_DE"){ // DEUTSCH
?>
<h1>Geschichte</h1>
Fast 50 Jahre nach seiner Gründung hat der Verein Arsenal – Institut für Film und Videokunst (ehemals Freunde der Deutschen Kinemathek) nicht nur eine 10.000 Titel umfassende Filmsammlung vorzuweisen. Er ist damit auch sein eigenes Archiv geworden: Im Gegensatz zu anderen Filmarchiven wurde hier niemals ein Sammlungsauftrag angenommen, den der Verein anhand definierter Kriterien durchzuführen hatte. Stattdessen entstand aus seiner eigenen kuratorischen und vermittelnden Praxis heraus immer wieder die Notwendigkeit, Filme verfügbar zu halten, damit sie überhaupt eine Öffentlichkeit in Berlin, in Deutschland oder in einigen Fällen auch weltweit erreichen konnten. Insofern spiegelt die Filmsammlung ein halbes Jahrhundert internationaler Kinogeschichte jenseits des Kommerziellen, anhand der lebendigen Geschichte einer Berliner Institution, die in ihrer Struktur weltweit einzigartig ist.
<br /><br />
"Ein Kino für öffentliche Vorführungen zu betreiben, gehört zu den unverzichtbaren Aufgaben eines Filmarchivs. Zwar gibt es einen alten und niemals endenden Streit unter Filmarchivaren, was wichtiger sei, Filme zu konservieren oder sie zu zeigen, jedoch wird niemand im Ernst bestreiten, dass die Organisation von regelmäßig stattfindenden Filmvorführungen auch zu den wesentlichen Zielen einer Kinemathek gehört. Einige Filmarchive, so die Pariser Cinémathèque Française, haben sogar über lange Jahre durch ihre Zyklen und Retrospektiven die Filmkultur ihres Landes beeinflusst." (Ulrich Gregor)
<br /><br />
Aus der Erkenntnis der Wichtigkeit von Vorführungen historischer Filme wurden 1963 die Freunde der Deutschen Kinemathek gegründet. Sie stellten sich zur Aufgabe, die Bestände der im gleichen Jahr gegründeten "Deutschen Kinemathek", die zunächst über sehr wenig Personal verfügte, der Öffentlichkeit zugänglich zu machen. Ab Mai 1963 haben die "Freunde" zunächst in der Berliner Akademie der Künste regelmäßig Filme gezeigt. Dabei gingen sie von einem zentralen Gedanken aus: der Kombination von Altem und Neuen. Bereits das erste Programm stellte neue deutsche Kurzfilme der Oberhausener Schule neben einen Klassiker des Expressionismus, Paul Lenis DAS WACHSFIGURENKABINETT (1924).
<br /><br />
Die Sammlung hat sich parallel zu den Aktivitäten der Kinoaufführungen (zunächst an der Akademie der Künste, seit 1970 im Kino Arsenal) entwickelt. Es begann damit, dass ein Mitarbeiter Lionel Rogosins, Jimmy Vaughan aus London, eines Tages seinen Film COME BACK AFRICA (1958) - einen Klassiker über die Apartheid-Politik in Südafrika - bei den "Freunden" deponierte mit dem Wunsch: "Bitte tut etwas für den Film!"
<br /><br />
In den späten 60er Jahren fanden vor allem die Kurzfilme lateinamerikanischer Filmemacher, aber auch z.B. Solanas' Filmtrilogie DIE STUNDE DER HOCHÖFEN Eingang in die Sammlung und damit Schutz vor den damaligen Diktaturen in Argentinien und Chile. Als 1971 erstmals das Internationale Forum des Jungen Films stattfand, machten es sich die Organisatoren zur Hauptaufgabe, die Filme nicht nur für ein zehntägiges Ereignis heranzuschaffen, sondern die ausgewählten, meist untertitelten Filme in Deutschland zu behalten und sie nach Möglichkeit der gewerblichen und nichtgewerblichen Filmarbeit zur Verfügung zu stellen.
<br /><br />
Der Filmstock vermehrte sich jährlich um ca. 30 - 40 Forumsfilme von zunächst noch unbekannten FilmemacherInnen. Jahrelang beherrschten manche dieser Filme die Programme der Kommunalen und Off-Kinos, so z.B. Herbert Bibermans SALT OF THE EARTH, die Filme von Derek Jarman, Ulrike Ottinger, Theo Angelopoulos, Manoel de Oliveira, Andrej Tarkowskij, Nagisa Oshima, Park Kwang-Su, Jonas Mekas, Mrinal Sen, Mani Kaul, Hou Hsiao-Hsien, Ousmane Sembène, Alexander Sokurow - die Liste ließe sich fast endlos fortsetzen. Rivettes Mammutfilm OUT1/SPECTRE oder die Dokumentarfilmepen SHOAH von Claude Lanzmann, MANUFACTURING CONSENT von Peter Wintonick und Mike Achbar, Filme von Marcel Ophuls, Frederick Wiseman, Robert Kramer, Yvonne Rainer, Raymond Depardon wurden durch die Arbeit der "Freunde" zu Klassikern eines "anderen Kinos". Noch heute ist die Auswahl des Forums ein nicht geringer Teil des Distributionsangebots.
<br /><br />
Auch kleinere Sammlungen fanden Eingang ins Arsenal-Archiv: Nach dem Mauerfall bemühten sich Erika und Ulrich Gregor erfolgreich um filmische Bestände der Sowjetischen Armee, die sonst vernichtet worden wären. Die Institution rettete eine Privatsammlung mit Hollywoodklassikern im 16mm-Format, die jahrelang die Programme der Kommunalen Kinos in Deutschland füllten und somit ganze Kinogenerationen filmisch sozialisierten. Gesamtwerke einzelner Filmschaffender wurden der Sammlung übergeben, darunter die Werke von Heinz Emigholz, Birgit Hein, Trinh T. Min-ha, Ulrike Ottinger, Helma Sanders-Brahms, Jack Smith, Frederick Wiseman. In den 1980er Jahren wurden durch die Arbeit des Forums und des Kino Arsenal weit über 100 afrikanische Filme gezeigt, in den 1990er Jahren standen das Filmland Indien und das Hongkongkino im Vordergrund. Die meisten der Filme wurden untertitelt oder zumindest mit deutschen oder englischen Textlisten versehen und fanden Eingang in die Sammlung.
<br /><br />
In den 1970er und 1980er Jahren entwickelte sich durch die Arbeit des Forums der Berlinale sowie eine enge Zusammenarbeit des Hauses mit dem Künstlerprogramm des Deutschen Akademischen Austauschdienstes (DAAD) eine enge Verbindung zum New American Cinema und damit zu Vertretern des Underground- und Avantgardefilms. Insbesondere der Mitarbeiter Alf Bold war am Aufbau eines umfassendes Netzwerkes beteiligt, indem er selbst viel Zeit in Nordamerika verbrachte und schließlich begann, mit Sachspenden zahlreicher Filmemacher eine umfassende Experimentalfilmsammlung aufzubauen, die neben noch unbekannten Juwelen Werke nahezu aller bekannten Vertreter wie Bruce Conner, Michael Snow, Hollis Frampton, Su Friedrich, Joyce Wieland, Ken Jacobs, Kenneth Anger, Jonas Mekas enthält.  Bis auf Bruce Conner, Hollis Frampton und Joyce Wieland, die inzwischen verstorben sind, sind all diese Regisseure dem Hause bis heute in vielen Projekten eng verbunden. Nach seinem Tod im Jahre 1994 hinterließ Bold der Institution einen Experimentalfilmfonds, mit dessen Hilfe diese Arbeit fortgeführt und kontinuierlich ausgebaut werden konnte: Im Jahre 2003 erhielt das Arsenal – Institut für Film und Videokunst den Innovationspreis des BKM für sein Distributionskonzept für Experimentalfilm und Videokunst, das nicht nur Verleihangebote für Kinos, sondern auch für Ausstellungen und andere mediale und kulturelle Kontexte beinhaltet.
<?php
} else { // ENGLISCH
?>
<h1>Background</h1>
Nearly 50 years after its founding, the Arsenal – Institute for Film and Video Art (formerly the Friends of the German Cinematheque) has not only amassed a film collection totaling more than 10,000 titles, it has also become its own archive. In contrast to other film archives, the institution has never had a pre-conceived mission statement for the collection, which the institution would then simply implement according to previously defined criteria. Instead, because of its own curatorial practice, it has been driven by a need to keep the films accessible, so that they could reach a audience in Berlin, in Germany, and in some cases even worldwide. For this reason, the film collection reflects a half century of international film history beyond the commercial sphere, by means of the living history of a Berlin institution that, in its structure, is unique in the world.
<br /><br />
"Running a cinema for public screenings is one of the indispensable tasks of a film archive. Of course, there is an old and never ending argument among film archivists over what is more important, to conserve or to exhibit, but no one would seriously propose that organizing regular film screenings is not also one of the essential goals of a cinematheque. Some film archives, such as the Cinémathèque Française in Paris, have even wielded great influence over the film culture of their countries over many year by means of their cycles and retrospectives." (Ulrich Gregor)
<br /><br />
Out of this awareness of the importance of screening historical films, the ‘Freunde der Deutschen Kinemathek’ was founded in 1963. They took on the task of providing public access to the holdings of the “Deutsche Kinemathek,” also founded the same year, but with initially very limited personnel. Starting in May 1963, the “Freunde” screened films regularly, initially in the Berlin Academy of the Arts. The starting point was one central ideal: the combination of old and new. Even the very first program presented new German short films from the ‘Oberhausen School’ alongside a classic of expressionism, Paul Leni’s WAXWORKS (1924).
<br /><br />
The collection developed parallel to the activities of film screenings (initially at the Academy of the Arts, since 1970 in the Arsenal Cinema). It began when a colleague of Lionel Rogosin’s, Jimmy Vaughan from London, one day deposited his film COME BACK AFRICA (1958)–a classic about the politics of Apartheid in South Africa–with the ‘Freunde’ along with the request: “Please do something for the film!”
<br /><br />
In the late sixties, short films from Latin American filmmakers, but also, for example, Solanas’s film trilogy THE HOURS OF THE FURNACES were taken into the collection, thus protecting them from the dictatorships at the time in Argentina and Chile. When in 1971 the first International Forum of New Cinema took place, the organizers took as their main task not only bringing together the films for a ten-day event, but also keeping selected, usually subtitled films in Germany, in order to make them as available as possible in commercial and non-commercial contexts.
<br /><br />
The stock of films increased annually by about 30-40 Forum films by as yet unknown filmmakers. For many years these films dominated the programs of the so-called kommunale cinemas (non-commercial film clubs) and off-cinemas, for example, films like Herbert Biberman’s SALT OF THE EARTH, the films of Derek Jarman, Ulrike Ottinger, Theo Angelopoulos, Manoel de Oliveira, Andrei Tarkowsky, Nagisa Oshima, Park Kwang-Su, Jonas Mekas, Mrinal Sen, Mani Kaul, Hou Hsiao-Hsien, Ousmane Sembène, Alexander Sokurow–the list could go on almost indefinitely. Rivette’s mammoth film OUT1/SPECTRE or documentary film epics like SHOAH by Claude Lanzmann, MANUFACTURING CONSENT by Peter Wintonick and Mike Achbar, films by Marcel Ophuls, Frederick Wiseman, Robert Kramer, Yvonne Rainer, Raymond Depardon were turned into classics of “another cinema” through the work of the ‘Freunde.’ Even today, the Forum selections are no less a part of the films on offer for distribution.
<br /><br />
In the 1970s and 1980s, close ties were developed with the New American Cinema and thus to representatives of underground and avant-garde film, due to the work of the Forum at the Berlin International Film Festival as well as in close collaboration with the artists’ program at the German Academic Exchange Service (DAAD). In particular, Alf Bold was active in building up a comprehensive network. He himself spent a great deal of time in North America, finally beginning to build up an extensive collection of experimental films made up of donations from numerous filmmakers, including nearly all the well-known figures in the field such as Bruce Conner, Michael Snow, Hollis Frampton, Su Friedrich, Joyce Wieland, Ken Jacobs, Kenneth Anger, Jonas Mekas, all of whom (with the exceptions of Conner, Frampton, and Wieland, who are no longer alive) work closely with the institute on many projects to this day. In addition, the collection holds many jewels by lesser-known filmmakers. On his death in 1994, Bold left the institution an experimental film fund, which allows this work to continue. In 2003 the Arsenal – Institute for Film and Video Art received the prize in innovation from the BKM for its distribution concept for experimental film and video art, which contains not only offerings for cinemas, but also for exhibitions and other media and cultural contexts.
<br /><br />
As a result of this work of many years, the executors of the estate of the queer underground icon Jack Smith consigned his complete film works to the institution in 2008. But other partial collections were also taken in. After the fall of the Berlin Wall, Erika and Ulrich Gregor went to great and successful efforts to obtain the film holdings of the Soviet Army, which otherwise would have been destroyed. The institution rescued a private collection, including Hollywood classics in 16mm, which had made up the programs in the kommunale cinemas in Germany for many years, thus having socialized whole generations of filmgoers. In the 1980s more than 100 African films were discovered through the work of the Forum and the Arsenal Cinema; in the 1990s India and Hong Kong took over the cinematic foreground. Most of the films were subtitled or at least provided with German or English text scripts, and found their way into the collection.
<br /><br />
<?php
} // ENDE
?>