# Optional routes, used if request does not directly resolve to a module, controller and action
#
routes = {
	example_route = {
		# Perform multisearch on text following /qs/ in a GET request
		method = GET,
		pattern = "/qs/{^search}",
		constraints = {
			"search" = "/([\\w ]+)/i"
		},
		to = {module = "", controller = "MultiSearch", action = "Index", params = {}}
	}
}